#!/bin/bash
#SBATCH -A CS4378T_Spring2013  # account name
#SBATCH -J p6_sjolsen          # job name
#SBATCH -o p6_sjolsen.%j       # name of the output and error file
#SBATCH -N 1                   # total number of nodes requested
#SBATCH -n 1                   # total number of tasks requested
#SBATCH -p gpu                 # queue name
#SBATCH -t 00:01:00            # expected maximum runtime (hh:mm:ss)

time ~sjolsen/mandelbrot/seahorse.bash 6000 8
